version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    schedule:
      interval: "weekly"
      day: "monday"
      time: "01:00"
      timezone: "UTC"
